### ISSUE TITLE
Infinite update when connected by ethernet

### ISSUE THREAD

**Issue by meatThejuicy** [IllusionMods/KKManager#41]
having the infamous infinte update but only when connected by ethernet, when connected by wifi the update proceeds fine.
weird.

The PC that is affected is linked by ethernet to another PC with WIFI.
Never had any particular connectivity problems linked to it.

The log shows before/after going with WIFI.
[KKManager.log](https://github.com/IllusionMods/KKManager/files/5757742/KKManager.log)

**Comment by ManlyMarco** [comment]
Not sure what the issue is. At what part exactly does it get stuck, just before the list of things to update?

**Comment by meatThejuicy** [comment]
> Not sure what the issue is. At what part exactly does it get stuck, just before the list of things to update?

This is what i get when connected by ethernet:
![Screenshot 2021-01-01 045049](https://user-images.githubusercontent.com/76819826/103433180-19f8cc00-4bed-11eb-9cef-a8678bea6812.png)
The updater basically seems stuck from the beggining, the progress bar continues to circle and no new text is presented.
Also no utilisation of CPU or disk in task manager.

(sorry if i may have not explained the issue clearly on the first post, so i'm going to rephrase it)
The first part of the log in the previous post shows when the application was opened while connected by ethernet.
It shows that the sources cannot be acceced citing "Failed to download Updates file Updates2.xml from betterrepack.com - One or more errors occurred." for all 3 sources.

However when connected by WIFI (as shown by the second half of the log) the updater can access the sources and successfully complete the updates.


This problem might be linked to my setup, but since i did not seem to have any similar problems with any other apps i thought other users might experience the same problem as i did.

I respect the work you do and will be checking the thread if you need more info.

**Comment by MrZackarias** [comment]
I'm experiencing the same thing, however I don't have wifi on this machine to check if it works.

**Comment by lj7711622** [comment]
i had cloned the project and update the FluentFtp :
Install-Package FluentFTP -Version 33.0.3
fixed!

**Comment by Openshut** [comment]
> 
> 
> i had cloned the project and update the FluentFtp :
> Install-Package FluentFTP -Version 33.0.3
> fixed!

I am also having this issue, with wifi and ethernet. How do I use this fix?
Thanks.

**Comment by lj7711622** [comment]
> > i had cloned the project and update the FluentFtp :
> > Install-Package FluentFTP -Version 33.0.3
> > fixed!
> 
> I am also having this issue, with wifi and ethernet. How do I use this fix?
> Thanks.

download and override the file.
https://mega.nz/folder/DXBWlD5b#syrKMSIq65YJFt9iq-gTkA

**Comment by meatThejuicy** [comment]
> > > i had cloned the project and update the FluentFtp :
> > > Install-Package FluentFTP -Version 33.0.3
> > > fixed!
> > 
> > 
> > I am also having this issue, with wifi and ethernet. How do I use this fix?
> > Thanks.
> 
> download and override the file.
> https://mega.nz/folder/DXBWlD5b#syrKMSIq65YJFt9iq-gTkA

Having the same issue with fix, but the logs are different:
[KKManager.log](https://github.com/IllusionMods/KKManager/files/5795647/KKManager.log)

**Comment by meatThejuicy** [comment]
> > > i had cloned the project and update the FluentFtp :
> > > Install-Package FluentFTP -Version 33.0.3
> > > fixed!
> > 
> > 
> > I am also having this issue, with wifi and ethernet. How do I use this fix?
> > Thanks.
> 
> download and override the file.
> https://mega.nz/folder/DXBWlD5b#syrKMSIq65YJFt9iq-gTkA

I seem to have a new problem since i applied the fix (still getting infinite update) :
[KKManager.log](https://github.com/IllusionMods/KKManager/files/5795721/KKManager.log)

**Comment by Openshut** [comment]
> 
> 
> > > > i had cloned the project and update the FluentFtp :
> > > > Install-Package FluentFTP -Version 33.0.3
> > > > fixed!
> > > 
> > > 
> > > I am also having this issue, with wifi and ethernet. How do I use this fix?
> > > Thanks.
> > 
> > 
> > download and override the file.
> > https://mega.nz/folder/DXBWlD5b#syrKMSIq65YJFt9iq-gTkA
> 
> I seem to have a new problem since i applied the fix (still getting infinite update) :
> [KKManager.log](https://github.com/IllusionMods/KKManager/files/5795721/KKManager.log)

Same for me.

**Comment by lj7711622** [comment]
> > > > i had cloned the project and update the FluentFtp :
> > > > Install-Package FluentFTP -Version 33.0.3
> > > > fixed!
> > > 
> > > 
> > > I am also having this issue, with wifi and ethernet. How do I use this fix?
> > > Thanks.
> > 
> > 
> > download and override the file.
> > https://mega.nz/folder/DXBWlD5b#syrKMSIq65YJFt9iq-gTkA
> 
> I seem to have a new problem since i applied the fix (still getting infinite update) :
> [KKManager.log](https://github.com/IllusionMods/KKManager/files/5795721/KKManager.log)

try to use ths StandaloneUpdater.exe(usage: open Initial Settings.exe and click update)

**Comment by Openshut** [comment]
> 
> 
> > > > > i had cloned the project and update the FluentFtp :
> > > > > Install-Package FluentFTP -Version 33.0.3
> > > > > fixed!
> > > > 
> > > > 
> > > > I am also having this issue, with wifi and ethernet. How do I use this fix?
> > > > Thanks.
> > > 
> > > 
> > > download and override the file.
> > > https://mega.nz/folder/DXBWlD5b#syrKMSIq65YJFt9iq-gTkA
> > 
> > 
> > I seem to have a new problem since i applied the fix (still getting infinite update) :
> > [KKManager.log](https://github.com/IllusionMods/KKManager/files/5795721/KKManager.log)
> 
> try to use ths StandaloneUpdater.exe(usage: open Initial Settings.exe and click update)

Ah, that worked. Sorry, should've tried that, thanks.

**Comment by meatThejuicy** [comment]
> > > > > > i had cloned the project and update the FluentFtp :
> > > > > > Install-Package FluentFTP -Version 33.0.3
> > > > > > fixed!
> > > > > 
> > > > > 
> > > > > I am also having this issue, with wifi and ethernet. How do I use this fix?
> > > > > Thanks.
> > > > 
> > > > 
> > > > download and override the file.
> > > > https://mega.nz/folder/DXBWlD5b#syrKMSIq65YJFt9iq-gTkA
> > > 
> > > 
> > > I seem to have a new problem since i applied the fix (still getting infinite update) :
> > > [KKManager.log](https://github.com/IllusionMods/KKManager/files/5795721/KKManager.log)
> > 
> > 
> > try to use ths StandaloneUpdater.exe(usage: open Initial Settings.exe and click update)
> 
> Ah, that worked. Sorry, should've tried that, thanks.

Seems to be working now. Thanks!

**Comment by ManlyMarco** [comment]
Servers are back to working normally so the issues should be resolved.
